services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - 5000:5000
    volumes:
      - ./mlflow:/mlflow
    environment:
      MLFLOW_TRACKING_URI: http://localhost:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root /mlflow
    restart: unless-stopped
  
  kedro:
    build:
      context: ./pipelines/ct
      dockerfile: Dockerfile.kedro
    volumes:
      - ./pipelines/ct:/app
    depends_on:
      - mlflow
    tty: true

# Airflow is managed by the official docker-compose in ./airflow/docker-compose.yaml
# To start all services: docker-compose -f docker-compose.yml -f airflow/docker-compose.yaml up -d
