data_pipeline:
  target: revenue
  train_size: 0.8
  eval_size: 0.1
  test_size: 0.1
  random_state: 42
  n_samples: 10000
  preprocessor_params:
    process_cols:
      - age
      - income
      - spending_score
      - loyalty_score
      - purchase_frequency
    standard_scaler:
      with_mean: True
      with_std: True

model_pipeline:
  mlflow_params:
    tracking_uri: "http://localhost:5000"
    experiment_name: "revenue_prediction"
  baseline_model_params:
    linear_regression:
      max_iter: 1000
      tol: 1e-3
    lightgbm:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 10
      verbose: -1
    ann:
      hidden_size: 32
      num_layers: 3
      learning_rate: 0.001
      batch_size: 32
      epochs: 100
  optimize_params:
    n_trials: 30
    study_name: "revenue_prediction"
    direction: "minimize"